version: '3.8'

services:
  apache:
    build:
      context: ./docker/apache
    container_name: iga_apache
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
    networks:
      - iga_network

  mysql:
    image: mysql:5.7
    container_name: iga_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iga
      MYSQL_USER: iga
      MYSQL_PASSWORD: iga
    ports:
      - "33306:3306"
    volumes:
      - ./docker/mysql/mysql-data:/var/lib/mysql
    networks:
      - iga_network

networks:
  iga_network:
    name: iga_network
    driver: bridge